/***************************************************************/
/*   This file was automatically generated by SideConf(TM).    */
/*   DO NOT EDIT.                                              */
/***************************************************************/

#ifdef DLL
#include "cwsdl.h"

sideC_dll_sim_mem_map_t sideC_dll_sim_mem_map[] = {
    {"g00", 0x00d80000},
    {"g01", 0x00d81000},
    {"g03", 0x00d82000},
    {"g04", 0x00d83000},
    {"g05", 0x00d84000},
    {"g06", 0x00d85000},
    {"g07", 0x00d86000},
    {"g08", 0x00d96000},
    {"g09", 0x00d97000},
};
long sideC_dll_sim_state_map[] = {
    /*func_get_chroma_0x states*/ 
    /*recon8x8 states*/ 
};
sideC_dll_sim_map_t sideC_dll_sim_map = {
    7, /*conf word count*/
    9, /*mem count*/
    2, /*conf count*/
    0, /*max state count*/
    0, /*max cnst count*/
};

#endif /*DLL*/
